### ISSUE TITLE
After upgrade to 3.20.0 get error with RadzenNumeric

### ISSUE THREAD

**Issue by broda02** [radzenhq/radzen-blazor#564]
**Describe the bug**
A Blazor WASM app using the RadzenNumeric I get the following trap: Radzen.numericOnInput is not a function 

**To Reproduce**
1. Use the numeric below:

<RadzenNumeric TValue="double" Min="@vm.ReadingMinimum" Max="@vm.ReadingMaximum" Class="w-100" @bind-Value=@vm.Reading Style="@entrystyle" Change="@(OnReadingChange)"/> 

**Expected behavior**
No trap like in 3.19.1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Max Os
 - Browser Edge
 - Version [e.g. 22] 103.0.1264.77

**Additional context**

**Comment by broda02** [comment]
TypeError: Radzen.numericOnInput is not a function 
at HTMLInputElement.onblur

**Comment by enchev** [comment]
Try to clear your browser cache. This is a new function required by the component part of latest Radzen.Blazor.js
